### ISSUE TITLE
8.8.6 Build FAILURE

### ISSUE THREAD

**Issue by mantisae** [ZeXtras/OpenZAL#18]
# ant zal-8.8.6
Output:
> Buildfile: /root/OpenZAL/build.xml
> 
> init:
>      [echo]  Building ZAL version 2.1.2 
> 
> zal-8.8.6:
>      [echo] devmode is false
>      [echo] Creating zal JAR for zimbra 8.8.6 ...
>      [echo] Preprocessing...
> [preprocess] modified 20 of 307 files
>     [javac] Compiling 307 source files to /root/OpenZAL/build/8.8.6_dev_false/jar
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Domain.java:27: error: cannot find symbol
>     [javac] import javax.annotation.Nullable;
>     [javac]                        ^
>     [javac]   symbol:   class Nullable
>     [javac]   location: package javax.annotation
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Mailbox.java:41: error: package org.apache.commons.dbutils does not exist
>     [javac] import org.apache.commons.dbutils.DbUtils;
>     [javac]                                  ^
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/ContinuationJetty.java:25: error: package org.eclipse.jetty.continuation does not exist
>     [javac] import org.eclipse.jetty.continuation.ContinuationSupport;
>     [javac]                                      ^
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/ContinuationJetty.java:31: error: package org.eclipse.jetty.continuation does not exist
>     [javac]   org.eclipse.jetty.continuation.Continuation mContinuation;
>     [javac]                                 ^
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Domain.java:117: error: cannot find symbol
>     [javac]   @Nullable
>     [javac]    ^
>     [javac]   symbol:   class Nullable
>     [javac]   location: class Domain
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Mailbox.java:2383: error: cannot find symbol
>     [javac]       DbUtils.closeQuietly(resultSet);
>     [javac]       ^
>     [javac]   symbol:   variable DbUtils
>     [javac]   location: class Mailbox
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Mailbox.java:2384: error: cannot find symbol
>     [javac]       DbUtils.closeQuietly(statement);
>     [javac]       ^
>     [javac]   symbol:   variable DbUtils
>     [javac]   location: class Mailbox
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Mailbox.java:2440: error: cannot find symbol
>     [javac]       DbUtils.closeQuietly(insertStatement);
>     [javac]       ^
>     [javac]   symbol:   variable DbUtils
>     [javac]   location: class Mailbox
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/Mailbox.java:2441: error: cannot find symbol
>     [javac]       DbUtils.closeQuietly(updateStatement);
>     [javac]       ^
>     [javac]   symbol:   variable DbUtils
>     [javac]   location: class Mailbox
>     [javac] /root/OpenZAL/tmpsrc/8.8.6/jar/org/openzal/zal/ContinuationJetty.java:35: error: cannot find symbol
>     [javac]     mContinuation = ContinuationSupport.getContinuation(req);
>     [javac]                     ^
>     [javac]   symbol:   variable ContinuationSupport
>     [javac]   location: class ContinuationJetty
>     [javac] Note: Some input files use or override a deprecated API.
>     [javac] Note: Recompile with -Xlint:deprecation for details.
>     [javac] Note: Some input files use unchecked or unsafe operations.
>     [javac] Note: Recompile with -Xlint:unchecked for details.
>     [javac] 10 errors
> 
> BUILD FAILED
> /root/OpenZAL/build.xml:818: The following error occurred while executing this line:
> /root/OpenZAL/build.xml:69: Compile failed; see the compiler error output for details.

Using the build dependencies linked in the readme I had to move them to ../build-commons to even get the thing to throw errors other than missing dependencies

Using 8.8.6 on Ubuntu 16.04

File Lists (after build attempt):
[build-commons-files.txt](https://github.com/ZeXtras/OpenZAL/files/1785708/build-commons-files.txt)
[OpenZAL-files.txt](https://github.com/ZeXtras/OpenZAL/files/1785709/OpenZAL-files.txt)

**Comment by DinoPuller** [comment]
Hello, sorry for late reply. Now if you pull new updates from git, this issue should be fixed.
